### ISSUE TITLE
Error posting layers to geoserver

### ISSUE THREAD

**Issue by jbeezley** [OpenGeoscience/dataqs#14]
I tried provisioning through vagrant, and I'm getting some errors when adding some of the data sources.  One of the failing commands is:

```
$ /home/vagrant/venvs/geonode/bin/python /home/vagrant/venvs/geonode/src/dataqs/dataqs/forecastio/forecastio_air.py
Not enabling BingMaps base layer as a BING_API_KEY is not defined in local_settings.py file.
Traceback (most recent call last):
  File "/home/vagrant/venvs/geonode/src/dataqs/dataqs/forecastio/forecastio_air.py", line 106, in <module>
    processor.run()
  File "/home/vagrant/venvs/geonode/src/dataqs/dataqs/forecastio/forecastio_air.py", line 86, in run
    self.post_geoserver(dst_file, self.layer_name)
  File "/home/vagrant/venvs/geonode/src/dataqs/dataqs/processor_base.py", line 352, in post_geoserver
    res.raise_for_status()
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 773, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error
```

The geoserver log looks like [this](https://gist.github.com/8f9dd676ffd0e9610bf1).

The similar error occurs with `wqp`.

```
$ /home/vagrant/venvs/geonode/bin/python /home/vagrant/venvs/geonode/src/dataqs/dataqs/wqp/wqp.py
Not enabling BingMaps base layer as a BING_API_KEY is not defined in local_settings.py file.
[updated] Layer wqp_api_ph_map (1/1)


Finished processing 1 layers in 0.0 seconds.

0 Created layers
1 Updated layers
0 Failed layers
0.000000 seconds per layer
Traceback (most recent call last):
  File "/home/vagrant/venvs/geonode/src/dataqs/dataqs/wqp/wqp.py", line 234, in <module>
    processor.run()
  File "/home/vagrant/venvs/geonode/src/dataqs/dataqs/wqp/wqp.py", line 209, in run
    self.update_indicator_table(result_csv)
  File "/home/vagrant/venvs/geonode/src/dataqs/dataqs/wqp/wqp.py", line 154, in update_indicator_table
    self.post_geoserver_vector(indicator + self.suffix)
  File "/home/vagrant/venvs/geonode/src/dataqs/dataqs/processor_base.py", line 189, in post_geoserver_vector
    res.raise_for_status()
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 773, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error
```

I had to restart the provisioning several times to get it to complete successfully, so it is possible the database ended up in an invalid state.

**Comment by aashish24** [comment]
@mbertrand any suggestions here?

**Comment by mbertrand** [comment]
My guess is it has something to do with user permissions, but haven't had time to really look into it yet.

**Comment by aashish24** [comment]
@jbeezley I resolved two issues when using ansible 2.0. The command worked for me.

Ref: https://github.com/OpenGeoscience/dataqs/pull/15

**Comment by jbeezley** [comment]
With ansible 2.0, I managed to get through most of it without issue.  Here are the steps I went through from a new VM:
- A permission error during `Create the forecastio coverage store`

```
IOError: [Errno 13] Permission denied: '/var/lib/tomcat7/webapps/geoserver/data/data/geonode/forecast_io_airtemp/forecast_io_airtemp_20160331T150000000Z.tif'
```
- `Restart supervisord` fails at the end with

```
Stopping Supervisor: supervisor.
Starting Supervisor: process already running.
```
- I had to manually restart supervisor, uwsgi, and nginx after provisioning to get everything to work.
- Reprovisioning fails with the following message unless you manually restart postgis:

```
unable to connect to database: could not connect to server: No such file or directory
    Is the server running locally and accepting
    connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
```
- When reprovisioning, it removed all previously existing layers from geoserver and `Create the wqp store` failed with the same geoserver message from my original post, but forecastio succeeded.

I'm still waiting to see if the scheduled celery processes succeed or not.

**Comment by aashish24** [comment]
thanks for the update @jbeezley. Did you try the master branch with my changes merged in? Also, I think I did (which was recommended) was after provisioning, I did 

`vagrant halt`
`vagrant up`

I know in the past we had do this because of some errors with services running. Also it is in the readme as well.

**Comment by jbeezley** [comment]
Yes, restarting the VM would probably have the same effect as restarting the services.

**Comment by aashish24** [comment]
Right, we actually have a note in the readme here:  (last line) https://github.com/OpenGeoscience/dataqs/blob/master/ansible/README.md

So I would say that this issue is not specific to your system. 

@mgrauer if you can confirm this, that would be great.

**Comment by aashish24** [comment]
@kotfic here is how you run the process manually: 

$ /home/vagrant/venvs/geonode/bin/python /home/vagrant/venvs/geonode/src/dataqs/dataqs/wqp/wqp.py

**Comment by aashish24** [comment]
this issue and bunch of other issues are now fixed in master. There were multiple problems including use of wrong jdk, permissions etc. The original issue was related to Java as I was able to replicate and fix in this PR: https://github.com/OpenGeoscience/dataqs/pull/26
